### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/Tail#1]
Вам осталось исправить совсем чуть-чуть, поэтому высылаю второей задание.

**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**tail**
Выделение из текстового файла его конца некоторого размера:
- fileN задаёт имя входного файла. Если параметр отсутствует, следует считывать входные данные с консольного ввода. Если параметров несколько, то перед выводом для каждого файла следует вывести его имя в отдельной строке.
- Флаг -o ofile задаёт имя выходного файла (в данном случае ofile). Если параметр отсутствует, следует выводить результат на консольный вывод.
- Флаг -с num, где num это целое число, говорит о том, что из файла нужно извлечь последние num символов.
- Флаг -n num, где num это целое число, говорит о том, что из файла нужно извлечь последние num строк.

Command line: tail [-c num|-n num] [-o ofile] file0 file1 file2 …

В случае, когда какое-нибудь из имён файлов неверно или указаны одновременно флаги -c и -n, следует выдать ошибку. Если ни один из этих флагов не указан, следует вывести последние 10 строк.

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by JohnKhandygo** [comment]
В целом код огонь. Очень низкое покрытие тестами + есть несколько замечаний.

**Comment by katorina** [comment]
Проверьте, пожалуйста

**Comment by JohnKhandygo** [comment]
Зачтено на 5.
