### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/Tail#3]
- [x] Читай внимательно условие задачи: не реализован ввод из нескольких файлов. Вместо этого зачем-то вывод в несколько файлов сделали.
- [x] В случае использования `-c` и ввода из консоли не сохраняются переносы строк. 
- [x] Неэффективно реализовано чтение из консоли и файла: Вы считываете содержиоме файла целиком в память, соответственно при больших объемах файлов программа может упасть мз-за нехватки памяти. 

**FYI** В java уже давно не принято называть интерфейсы c `I`. Это необходимо было раньше, когда не существовало мощных IDE, а из кода надо было понимать, что обрабатывается интерфейс или класс. Сейчас та же idea все красиво подсвечивает, можно быстро перейти к определению той или иной сущности в коде, зато использование подобных суффкисов/префиксов портит readability кода.

**Comment by katorina** [comment]
С этим вроде всё

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущих комментариях актуально.

- [x] В условии задачи есть пример того, как должен выглядеть вызов разработанной программы (с точностью до ее названия). У Вас разбор аргументов не так организован. Так и не понял, почему Вы не захотели использовать какую-нибудь библиотеку для этого (на лекциях точно рассказывали).
- [x] В `Reader`'ах, которые работают со строками Вы используете циклический буффер на списках. Это крайне неэффективно из-за того, что удаление первого элемента списка приводит к копированию всех остальных элементов массива, что в свою очередь имеет сложность `O(n)`. Вам необходимо использовать другую структуру данных, для которой удаление первого элемента "типично".
- [x] Логика работы в случае использования флага `-c` в принципе реализована некорректно. 

> Читай внимательно условие задачи: не реализован ввод из нескольких файлов. Вместо этого зачем-то вывод в несколько файлов сделали.

**Внимательно** прочитайте условие задачи. Некорректно реализована работа программы в случае чтения из нескольких файлов.

> В случае использования -c и ввода из консоли не сохраняются переносы строк.

Насколько я вижу, все еще верно. Либо учитываете некорректным образом. 

> Неэффективно реализовано чтение из консоли и файла.

Неэффективно реализовано чтение из файла. Метод `File::readLines` считывает все содержимое файла в память. Об этом даже в [документации](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/read-lines.html) написано.

**Comment by JohnKhandygo** [comment]
- [ ] При использования флага `-c` маркеры переноса строки учитываются как отдельные символы. В windows маркер переноса строки --- это вообще два `char`'а: `\r\n`. Этот случай должен быть покрыт тестами.

**Comment by katorina** [comment]
Залила тесты.
А дедлайн по третьему заданию сегодня, верно же? Если да, можете сказать, во сколько?

**Comment by JohnKhandygo** [comment]
Как обычно.

**Comment by JohnKhandygo** [comment]
Вы что-то не так поняли в замечании. Вот возьмем тестовый сценарий `checkConsoleReaderBySymbol`. В нем последние 5 символов это последняя строка `5678` и конец второй строки `4`. Итого в выводе должно получиться 
```
4
5678
```
То есть управляющие последовательности символов (типа `\n`) не должны учитываться.

**Comment by katorina** [comment]
Вроде все
