### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/Tail#4]
- [x] В kotlin (так же, как и в java) принято все классы именовать в [UpperCamelCase](http://wiki.c2.com/?UpperCamelCase).
- [x] Очень низкое покрытие кода: многие сценарии использования не протестированы.
- [x] Файл output.txt --- побочный продукт работы тестов, его не должно быть в проекте. Вместо этого лучше использовать временный (tmp, temporary) директории.
- [x] Файл input/source.txt конечно нужен для тестов, однако его принято складывать в директорию тестовых ресурсов в соответствии со стандартной структорой проекта.

**Comment by katorina** [comment]
Добавила тестов

**Comment by JohnKhandygo** [comment]
Все, что не помечено галочками в предыдущих комментариях актуально.

> Очень низкое покрытие кода: многие сценарии использования не протестированы.

Не покрыты ввод/вывод из/в консоль. Делать это не очень приятно, но [возможно](https://stackoverflow.com/questions/1119385/junit-test-for-system-out-println). Некоторые добавленные тесты не проверяют ничего. Не покрыт тестами случаи использования `-c` с переносом строк.
